### ISSUE TITLE
Provide ability to override image

### ISSUE THREAD

**Issue by yashbhutwala** [VerizonMedia/kubectl-flame#1]
I am running into this issue in my cluster since we disable images tagged with latest.  Generally, it's good to provide a way to override the image.

admission webhook "admission.XXX.com" denied the request: Forbidden: Usage of latest tag for images is prohibited. Resource kubectl-flame-f2a23476-f254-4558-afee-6401ab8fe5f1 has a container kubectl-flame that contains image tag as `latest`

**Comment by edeNFed** [comment]
Hi @yashbhutwala, sorry that you had this issue.
This will be fixed in the next version which will be released in the next couple of days.
Thanks

**Comment by ryanlewis** [comment]
Also interested in this functionality, as we only allow images from a mirror.
