### ISSUE TITLE
Can flame pod works with istio?

### ISSUE THREAD

**Issue by zhiyanliu** [VerizonMedia/kubectl-flame#13]
Hi, it seems kubectl-flame pod doesn't work with istio sidecar. I got follow error when I execute the example command on the pod in my istio-enabled namespace.

```
> kubectl flame POD-ID -t 1m -f /tmp/flamegraph.svg -l java CONTAINER-NAME
Verifying target pod ... ✔
Launching profiler ... ✔
❌
a container name must be specified for pod kubectl-flame-831b66f2-5a01-4b92-b821-24c23277fa1e-8k9vf, choose one of: [kubectl-flame istio-proxy] or one of the init containers: [istio-validation]
```

I can try to disable istio sidecar injection on this namespace but I think the side-effect is too heavy.
Or a solution is to give a way to add the annotation ``sidecar.istio.io/inject: "false"`` to the kubectl-flame pod and make it to be aware I think.

Any idea?
Thanks!

**Comment by edeNFed** [comment]
Thanks for opening this issue, fixed in #16 
You can easily get the latest kubectl-flame version by running `kubectl krew upgrade`

**Comment by zhiyanliu** [comment]
Nice, thanks for working on it! will have a try later.

**Comment by zhiyanliu** [comment]
In v0.1.4, the profiler can be now lunched successfully but unfortunately I got an error during profiling, will open a new issue to track it.

About the PR/fix of this issue, may I respectfully know your thoughts on my follow consideration? @edeNFed 

I see you disabled istio sidecar injection by adding the ``sidecar.istio.io/inject: "false"`` annotation to the job, it works for istio however I trend to think it's a very case-by-case method which only works for istio. Sidecar is a common pattern in k8s world, beside istio it has been leveraged by more and more toolset which needs to inject the sidecar to the target pod to co-work with outside controller, with the method it means we need to add more special annotations to the flame code base to handle different toolset in future, even need special logic for these toolsets don't support annotation-based sidecar disabling.

So I'm thinking do you think we can just skip any other (injected) container in the job pod except our flame container strictly in such logic (I didn't read this pice of code yet)? IMO this general method can take care any sidecar injection beside istio one only.

Thanks again!

**Comment by edeNFed** [comment]
@zhiyanliu I totally agree. The istio PR was just a quick fix to avoid blocking istio users while thinking about a complete solution to sidecar / init-containers injection.
As the flamegraph's data is passed by reading the Pod's logs we can change it to read specifically from the profiler container. However, this is still not bulletproof since some init container/sidecar could potentially interfere with the profiler process. I am currently investigating whether there is a way to avoid any mutation by mutation hooks.
What do you think?

**Comment by zhiyanliu** [comment]
Hi @edeNFed , thanks for sharing your idea with me. It make sense to me a lot, both ad-hoc fix and longterm idea.

For the longterm one, my quick thoughts are:

- if disabling any mutation/injection has side-effect for some user/usercase, do our solution need this kind of "limitation"?
- it seems there is no such sidecar/init-container disabling switch in kubernetes/upstream-plan, sorry no?
