### ISSUE TITLE
[Feature] Be able to specify resource requests and limits for jobs

### ISSUE THREAD

**Issue by obitech** [VerizonMedia/kubectl-flame#29]
Hi,

first of all thank you for this nice plugin 🎉 

It would be really nice to be able to specify CPU/Memory requests and limits on the pods that are launched, I image we could add a field in `TargetDetails` or create a new struct which would allow further customization of the created JobSpec. We could then also pass labels, annotations, etc.

WDYT? If you want I could draft a PR too 🙂

Cheers,
Alex

**Comment by edeNFed** [comment]
Hi @obitech 
I really liked this idea.
If you could draft a PR for it that's will be great!

**Comment by obitech** [comment]
@edeNFed thanks for your quick reply. I'll try to work on it over the holidays. Any suggestions regarding the architecture? Should we add it to an existing type, create a new one, etc? If not I'll try to come up with something and then we can discuss it in review.

**Comment by edeNFed** [comment]
I don't have a specific design in mind. Feel free to come up with something.

**Comment by edeNFed** [comment]
Hi @obitech 
Just released `v0.1.8` with all the latest changes. You can easily update via `kubectl krew upgrade`
