### ISSUE TITLE
[Feature] Allow to choose profiling event type

### ISSUE THREAD

**Issue by u6f6o** [VerizonMedia/kubectl-flame#30]
Hi, 

I would propose that we add an option to specify the profiling mode. The github page states some of these and especially the allocation mode would be interesting for us:  

> -e event - the profiling event: cpu, alloc, lock, cache-misses etc. Use list to see the complete list of available events.

As far as I can see, the profiling mode is currently hardcoded: https://github.com/VerizonMedia/kubectl-flame/blob/5cb73b39e20a9998308c6b1960add543da23558f/agent/profiler/jvm.go#L47

If you agree that this could be useful, I'd come up with a PR. 

Cheers, u6f6o

**Comment by edeNFed** [comment]
Hi @u6f6o 
Sounds like a great idea to me.
Looking forward to this PR.
Thanks
