### ISSUE TITLE
Bug fix from issue added in #42

### ISSUE THREAD

**Issue by italux** [VerizonMedia/kubectl-flame#46]
## Description

Even after the changes applied on #42, the reported error still happen and this was due to a missing argument (aka `--event`) and also the validation of the `--pgrep`

**Comment by italux** [comment]
@edeNFed Sorry for the trouble, I found the issue between my local binary and the new version, and the fix proposal (_double-check this time_) is on #45. /cc @fyqls

**Comment by edeNFed** [comment]
No worries merged to `v0.2.1`
