### ISSUE TITLE
kubectl-flame does not take into account the node taints

### ISSUE THREAD

**Issue by casidiablo** [VerizonMedia/kubectl-flame#5]
I tried to profile a pod that runs on a certain type of node that has a taint, e.g.:

```node.yaml
taints:
  - effect: NoSchedule
    key: some-key
    value: some-value 
```

The job/pod that is launched by kubectl-flame, however, does not have tolerations for such taints, which makes it impossible to actually run the pod

**Comment by casidiablo** [comment]
I see... so specifying `nodeName` "disables" the taint or make it irrelevant?

**Comment by yashbhutwala** [comment]
it bypasses the k8s scheduler totally and corresponding kubelet on the node will pickup the workload.

**Comment by edeNFed** [comment]
Hi @casidiablo @yashbhutwala 
This issue is now fixed, if you installed via krew upgrading is as simple as:
`kubectl krew upgrade`
